[package]
name = "ffrostfall/keyform"
version = "0.0.0-b"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["build", "build/*", "default.project.json", "wally.lock", "wally.toml"]