[package]
name = "ffrostflame/keyform"
version = "0.2.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "ffrostflame/luausignal@0.1.3"
TableKit = "ffrostflame/tablekit@0.2.2"