return {
	["101"] = "KeyNameEmpty",
	["102"] = "KeyNameLimit",
	["103"] = "ValueNotAllowed",
	["104"] = "CantStoreValue",
	["105"] = "ValueTooLarge",

	["301"] = "GetAsyncThrottle",
	["302"] = "SetAsyncThrottle",
	["303"] = "IncreAsyncThrottle",
	["304"] = "UpdateAsyncThrottle",
	["305"] = "GetSortedThrottle",
	["306"] = "RemoveAsyncThrottle",

	["401"] = "DataModelNoAccess",
	["402"] = "LuaWebSrvsNoAccess",
	["403"] = "StudioAccessToApisNotAllowed",
	["404"] = "InternalError",

	["501"] = "InternalError",
	["502"] = "RequestRejected",
	["503"] = "InternalError",
	["504"] = "InternalError",
	["505"] = "InternalError",

	["511"] = "AttributeSizeTooLarge",
	["512"] = "UserIdLimitExceeded",
	["513"] = "AttributeFormatError",
}
